-- (Q1) Compute breakdown of properties per school code
-- (Q1b) Compute breakdown of properties per school code, order in decreasing order of number of properties
-- (Q2) Compute breakdown of properties per school district name, order in decreasing order of number of properties
-- (Q3) Create view that computes breakdown of properties per school district name
-- (Q4) Rewrite Q2 using view defined in Q3 
-- (Q5) How many school districts are there?
-- (Q6) List school districts in decreasing order of properties
-- (Q7) List the school district with the highest number of properties
-- (Q8) What is the highest number of properties for a single school district?
-- (Q9) List the school district with the highest number of properties (and handle ties)
-- (Q9b) List the school district with the highest number of properties (and handle ties) - version 2
-- (Q10) List the school district with 50% over the average number of properties (and handle ties)
-- (Q11) How much is the sum of the county assessed fair market value of all properties in the county?
-- (Q12) What is the breakdown of number of properties for the different tax codes?
-- (Q13) How much is the sum of the county assessed fair market value of all properties in the county 
--       for each of the different tax codes?
-- (Q14) What is the total county assessed fair market value for all properties per school district
-- (Q15) What is the total county assessed fair market value for all TAXABLE properties per school district
-- (Q16) What is the average county assessed fair market value for all TAXABLE properties per school district
-- (Q17) What is the total difference between county-assessed fair market value and saleprices?
-- (Q18) What is the total county-assessed fair market value?
-- (Q19) What is the total saleprices?
-- (Q20) What is the total difference between county-assessed fair market value and saleprices PER school district?
