t = linspace(0, 1000, 1000);
x_t = exp(t);
y_t = -1*exp(t);
xb = exp(-t);
yb = exp(-t);
hold on;
plot(x_t, y_t);
plot(xb, yb);
plot(-1*x_t, y_t);
plot(x_t, x_t);
plot(-1*xb, yb);
plot(xb, xb);
plot(xb, -1*xb);
plot(xb, -1*yb);
plot(-1*xb, xb);
plot(-1*xb, -1*xb);
plot(yb, yb);
plot(-1*x_t, x_t);
plot(-1*x_t, -1*x_t);
plot(x_t, -1*x_t);
title('Problem 9');
xlabel('X(t)');
ylabel('Y(t)');
axis([-4 4 -4 4]);