# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ece1195/labs/lab1/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_adder_subtractor_0_0/Lab_1_adder_subtractor_0_0.xci
# IP: The module: 'Lab_1_adder_subtractor_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece1195/labs/lab1/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_adder_subtractor_0_0/src/full_adder_0_1/full_adder_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_0 || ORIG_REF_NAME==full_adder_0} -quiet] -quiet

# IP: C:/ece1195/labs/lab1/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_adder_subtractor_0_0/Lab_1_adder_subtractor_0_0.xci
# IP: The module: 'Lab_1_adder_subtractor_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ece1195/labs/lab1/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_adder_subtractor_0_0/src/full_adder_0_1/full_adder_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_0 || ORIG_REF_NAME==full_adder_0} -quiet] -quiet
