# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_processing_system7_0_0/lab_3_processing_system7_0_0.xci
# IP: The module: 'lab_3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ece1195/labs/lab3/lab_3/ip/lab_3_processing_system7_0_0/lab_3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_processing_system7_0_0/lab_3_processing_system7_0_0.xci
# IP: The module: 'lab_3_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ece1195/labs/lab3/lab_3/ip/lab_3_processing_system7_0_0/lab_3_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_3_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
