# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/ece1195/labs/lab3/lab_3/lab_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3 || ORIG_REF_NAME==lab_3} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_processing_system7_0_0/lab_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_processing_system7_0_0 || ORIG_REF_NAME==lab_3_processing_system7_0_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_axi_regmap_0_0/lab_3_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_axi_regmap_0_0 || ORIG_REF_NAME==lab_3_axi_regmap_0_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_ps7_0_axi_periph_0/lab_3_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_rst_ps7_0_100M_0/lab_3_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_top_level_0_0/lab_3_top_level_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_top_level_0_0 || ORIG_REF_NAME==lab_3_top_level_0_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_slicer_high_0_0/lab_3_slicer_high_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_slicer_high_0_0 || ORIG_REF_NAME==lab_3_slicer_high_0_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_slicer_low_0_0/lab_3_slicer_low_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_slicer_low_0_0 || ORIG_REF_NAME==lab_3_slicer_low_0_0} -quiet] -quiet

# IP: c:/ece1195/labs/lab3/lab_3/ip/lab_3_auto_pc_0/lab_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_auto_pc_0 || ORIG_REF_NAME==lab_3_auto_pc_0} -quiet] -quiet

# XDC: C:/ece1195/labs/lab3/lab_3/lab_3_ooc.xdc
